### ISSUE TITLE
extraction of xlsx not working

### ISSUE THREAD

**Issue by ThHanke** [Mat-O-Lab/TablesToCSV#9]
tryed [this](https://github.com/Mat-O-Lab/TablesToCSV/raw/main/examples/Z-Windrepair_Testproben1.xlsx) and it failed

**Comment by rfechner** [comment]
Problem is, that passing the link as a raw link like "https://github.com/Mat-O-Lab/TablesToCSV/raw/main/examples/Z-Windrepair_Testproben1.xlsx" will result the program to crash.

We are expecting a default link like https://github.com/Mat-O-Lab/TablesToCSV/blob/main/examples/Z-Windrepair_Testproben1.xlsx OR the already fixed link 'https://raw.githubusercontent.com/Mat-O-Lab/TablesToCSV/main/examples/Z-Windrepair_Testproben1.xlsx'.

Real error-checking would include new regex checks and or analyzing the response, in case we received HTML code as response... My suggestion: The given link should not be used, implement code which catches this exact problem and converts the given link to a regular link.

**Comment by rfechner** [comment]
I implemented a small piece of code, that checks for this exact type of link, then flashes an error message.
